import PDFDocument from 'pdfkit';
import { PDFDocument as LibPDFDocument, rgb } from 'pdf-lib';
import sharp from 'sharp';
import path from 'path';
import fs from 'fs';
import prisma from '../../utils/prisma.js';
import { getStorageService } from '../storage/index.js';
import { sortTravelItemsByJourney } from '../../utils/sortTravelItems.js';

// ── Fonts ───────────────────────────────────────────────────────────────────
const BUNDLED_FONT_DIR = path.join(__dirname, 'fonts');
const SYSTEM_FONT_DIR = '/usr/share/fonts/truetype/liberation';
const FONT_DIR = fs.existsSync(path.join(BUNDLED_FONT_DIR, 'LiberationSans-Regular.ttf'))
  ? BUNDLED_FONT_DIR
  : SYSTEM_FONT_DIR;
const FONT_REGULAR = path.join(FONT_DIR, 'LiberationSans-Regular.ttf');
const FONT_BOLD    = path.join(FONT_DIR, 'LiberationSans-Bold.ttf');
const FONT_ITALIC  = path.join(FONT_DIR, 'LiberationSans-Italic.ttf');

// ── Layout constants ────────────────────────────────────────────────────────
const PAGE_W = 595.28;      // A4 width in pts
const MARGIN_H = 50;        // Left/right margins
const CONTENT_W = PAGE_W - MARGIN_H * 2;
const HEADER_Y  = 14;       // Header text y
const HEADER_LINE_Y = 46;   // Separator line y below header
const FOOTER_Y  = 826;      // Footer text y (near bottom)
const CONTENT_TOP = 58;     // Top margin for content (below header line)

// ── Label maps ──────────────────────────────────────────────────────────────
const TRANSPORT_LABELS: Record<string, string> = {
  PLANE: 'Flight', TRAIN: 'Train', BUS: 'Bus',
  CAR: 'Car', FERRY: 'Ferry', OTHER: 'Other',
};

const DOC_TYPE_LABELS: Record<string, string> = {
  FLIGHT_INVOICE: 'Flight Invoice',
  FLIGHT_BOARDING_PASS: 'Boarding Pass',
  TRAIN_TICKET: 'Train Ticket',
  BUS_TICKET: 'Bus Ticket',
  FUEL_RECEIPT: 'Fuel Receipt',
  GREEN_TRAVEL_DECLARATION: 'Green Travel Declaration',
  HOTEL_INVOICE: 'Hotel Invoice',
  BANK_TRANSACTION: 'Bank Transaction',
  LUGGAGE_INVOICE: 'Luggage Invoice',
  INTERRAIL_PASS: 'Interrail Pass',
  OTHER: 'Other Document',
};

// ── Helpers ─────────────────────────────────────────────────────────────────
function formatDate(d: Date | string | null | undefined): string {
  if (!d) return '—';
  const dt = typeof d === 'string' ? new Date(d) : d;
  return `${String(dt.getDate()).padStart(2, '0')}/${String(dt.getMonth() + 1).padStart(2, '0')}/${dt.getFullYear()}`;
}

function formatEur(amount: number | null | undefined): string {
  if (amount == null) return '—';
  return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(amount);
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// ── Structured PDF (PDFKit) ──────────────────────────────────────────────────

async function buildStructuredPdf(participantId: string): Promise<Buffer> {
  // Load full participant data
  const participant = await prisma.participant.findUnique({
    where: { id: participantId },
    include: {
      project: { include: { organisation: true } },
      documents: { orderBy: { uploadDate: 'asc' } },
      travelItems: { orderBy: { departureDate: 'asc' } },
      travelBookings: true,
      declarationsOnHonor: true,
      declarationsOfTravel: true,
      reimbursementSummary: true,
    },
  });

  if (!participant) throw new Error('Participant not found');
  participant.travelItems = sortTravelItemsByJourney(participant.travelItems);

  const exportTimestamp = new Date().toLocaleString('en-GB', {
    day: '2-digit', month: '2-digit', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
    timeZone: 'UTC',
  }) + ' UTC';

  const participantFullName = `${participant.firstName} ${participant.lastName}`;
  const projectRef = participant.project.name;
  const headerLeft = participantFullName;
  const headerRight = projectRef;

  let pageNum = 0;

  const footerText =
    `Generated by EasyReimburse on ${exportTimestamp}    ` +
    'This file reflects the stored data at time of export.';

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 0, // We handle all positioning manually
      bufferPages: false,
      info: {
        Title: 'Erasmus+ Travel Reimbursement Audit File',
        Author: 'EasyReimburse',
        Subject: `Participant Audit Dossier – ${participantFullName}`,
      },
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Register fonts
    doc.registerFont('R', FONT_REGULAR);
    doc.registerFont('B', FONT_BOLD);
    doc.registerFont('I', FONT_ITALIC);

    // ── Running header/footer on every page ─────────────────────────────────
    doc.on('pageAdded', () => {
      pageNum++;
      const isFirstPage = pageNum === 1;

      if (!isFirstPage) {
        // Header: left = participant name, right = page number
        doc.font('R').fontSize(8).fillColor('#555555')
          .text(headerLeft, MARGIN_H, HEADER_Y, { width: CONTENT_W * 0.7, lineBreak: false });
        doc.font('R').fontSize(8).fillColor('#555555')
          .text(`${headerRight}`, MARGIN_H, HEADER_Y, { width: CONTENT_W, align: 'right', lineBreak: false });

        // Separator line
        doc.moveTo(MARGIN_H, HEADER_LINE_Y)
          .lineTo(PAGE_W - MARGIN_H, HEADER_LINE_Y)
          .strokeColor('#cccccc').lineWidth(0.5).stroke();

        // Footer
        doc.font('I').fontSize(7).fillColor('#999999')
          .text(footerText, MARGIN_H, FOOTER_Y, { width: CONTENT_W, align: 'left', lineBreak: false });

        // Reset for content
        doc.fillColor('#000000').fontSize(12).font('R');
        doc.x = MARGIN_H;
        doc.y = CONTENT_TOP;
      }
    });

    // ── SECTION 1: Cover ────────────────────────────────────────────────────
    doc.x = MARGIN_H;
    doc.y = 160;

    // Title
    doc.font('B').fontSize(22).fillColor('#111111')
      .text('Erasmus+ Travel Reimbursement Audit File', MARGIN_H, 160, {
        width: CONTENT_W, align: 'center',
      });

    doc.font('R').fontSize(14).fillColor('#555555')
      .text('Participant Audit Dossier', MARGIN_H, doc.y + 12, {
        width: CONTENT_W, align: 'center',
      });

    // Divider
    const divY = doc.y + 28;
    doc.moveTo(MARGIN_H, divY).lineTo(PAGE_W - MARGIN_H, divY)
      .strokeColor('#cccccc').lineWidth(1).stroke();

    // Metadata grid (two columns)
    const metaTop = divY + 20;
    const col1X = MARGIN_H;
    const col2X = MARGIN_H + CONTENT_W / 2 + 10;
    const colW  = CONTENT_W / 2 - 10;

    function metaRow(label: string, value: string, x: number, y: number): number {
      doc.font('B').fontSize(9).fillColor('#888888').text(label.toUpperCase(), x, y, { width: colW, lineBreak: false });
      doc.font('R').fontSize(11).fillColor('#111111').text(value, x, y + 14, { width: colW });
      return doc.y + 6;
    }

    const org = participant.project.organisation;
    const orgName = org?.legalName || org?.name || '—';
    const orgVat = org?.vatNumber || null;

    const projectStart = formatDate(participant.project.startDate);
    const projectEnd   = formatDate(participant.project.endDate);

    let leftY  = metaTop;
    let rightY = metaTop;

    // Left column
    doc.font('B').fontSize(9).fillColor('#888888').text('ORGANISATION', col1X, leftY, { width: colW, lineBreak: false });
    doc.font('R').fontSize(11).fillColor('#111111').text(orgName, col1X, leftY + 14, { width: colW });
    leftY = doc.y + 6;

    if (orgVat) {
      doc.font('B').fontSize(9).fillColor('#888888').text('VAT NUMBER', col1X, leftY, { width: colW, lineBreak: false });
      doc.font('R').fontSize(11).fillColor('#111111').text(orgVat, col1X, leftY + 14, { width: colW });
      leftY = doc.y + 6;
    }

    doc.font('B').fontSize(9).fillColor('#888888').text('PROJECT TITLE', col1X, leftY, { width: colW, lineBreak: false });
    doc.font('R').fontSize(11).fillColor('#111111').text(participant.project.name, col1X, leftY + 14, { width: colW });
    leftY = doc.y + 6;

    doc.font('B').fontSize(9).fillColor('#888888').text('PROJECT DATES', col1X, leftY, { width: colW, lineBreak: false });
    doc.font('R').fontSize(11).fillColor('#111111').text(`${projectStart} – ${projectEnd}`, col1X, leftY + 14, { width: colW });
    leftY = doc.y + 6;

    // Right column
    doc.font('B').fontSize(9).fillColor('#888888').text('PARTICIPANT', col2X, rightY, { width: colW, lineBreak: false });
    doc.font('R').fontSize(11).fillColor('#111111').text(participantFullName, col2X, rightY + 14, { width: colW });
    rightY = doc.y + 6;

    doc.font('B').fontSize(9).fillColor('#888888').text('COUNTRY', col2X, rightY, { width: colW, lineBreak: false });
    doc.font('R').fontSize(11).fillColor('#111111').text(participant.country, col2X, rightY + 14, { width: colW });
    rightY = doc.y + 6;

    doc.font('B').fontSize(9).fillColor('#888888').text('DATE OF EXPORT', col2X, rightY, { width: colW, lineBreak: false });
    doc.font('R').fontSize(11).fillColor('#111111').text(exportTimestamp, col2X, rightY + 14, { width: colW });
    rightY = doc.y + 6;

    // Cover footer
    const coverFooterY = 800;
    doc.font('I').fontSize(7).fillColor('#999999')
      .text(footerText, MARGIN_H, coverFooterY, { width: CONTENT_W, align: 'left', lineBreak: false });

    // ── SECTION 2: Participant Summary ──────────────────────────────────────
    doc.addPage();
    doc.x = MARGIN_H;
    doc.y = CONTENT_TOP;

    sectionHeading(doc, 'Participant Summary');

    const summary = participant.reimbursementSummary;
    const simplifiedRoute = `${participant.country} → ${participant.project.country} → ${participant.country}`;

    const summaryRows: [string, string][] = [
      ['Participant Name',              participantFullName],
      ['Country of Origin',            participant.country],
      ['Simplified Travel Route',      simplifiedRoute],
      ['Total Travel Items',           String(participant.travelItems.length)],
      ['Total Declared Travel Amount', formatEur(summary?.totalEur)],
      ['Maximum Eligible Reimbursement', summary?.maxReimbursementAllowed
        ? formatEur(summary.maxReimbursementAllowed) +
          (participant.maxReimbursementOverride != null ? ' (individual limit)' : '')
        : 'Not configured'],
      ['Final Reimbursed Amount',      formatEur(summary?.amountToReimburse)],
    ];

    drawTable(doc, summaryRows, doc.y + 8);

    // ── Payment & Address Details (for the accountant) ──────────────────────
    const addressParts = [
      participant.personalAddress,
      [participant.personalPostalCode, participant.personalCity].filter(Boolean).join(' '),
      participant.personalCountry,
    ].filter((p) => p && p.trim().length > 0);

    const paymentRows: [string, string][] = [];
    if (participant.bankAccountHolderName) paymentRows.push(['Account Holder', participant.bankAccountHolderName]);
    // IBAN is stored space-free (accountant requirement) — print as-is.
    if (participant.bankAccountIban) paymentRows.push(['IBAN', participant.bankAccountIban]);
    if (participant.bankAccountBic) paymentRows.push(['BIC / SWIFT', participant.bankAccountBic]);
    if (participant.bankName) paymentRows.push(['Bank Name', participant.bankName]);
    if (addressParts.length > 0) paymentRows.push(['Address', addressParts.join(', ')]);

    if (paymentRows.length > 0) {
      doc.moveDown(1.2);
      sectionHeading(doc, 'Payment & Address Details');
      drawTable(doc, paymentRows, doc.y + 8);
    }

    // ── SECTION 3: Travel Items Breakdown ───────────────────────────────────
    doc.moveDown(1.5);
    sectionHeading(doc, 'Travel Items Breakdown');
    doc.moveDown(0.5);

    if (participant.travelItems.length === 0) {
      doc.font('I').fontSize(10).fillColor('#888888').text('No travel items recorded.', MARGIN_H, doc.y);
    }

    for (let i = 0; i < participant.travelItems.length; i++) {
      const item = participant.travelItems[i];

      // Ensure there is enough space for at least a heading + a couple lines
      if (doc.y > 680) doc.addPage();

      const itemTopY = doc.y;

      // Item header bar (light gray)
      const modeLabel = TRANSPORT_LABELS[item.modeOfTransport] || item.modeOfTransport;
      const itemHeaderText = `#${i + 1}  ${modeLabel}  –  ${item.fromLocation} → ${item.toLocation}`;

      drawItemHeader(doc, itemHeaderText, itemTopY);
      doc.y = itemTopY + 22;

      // Key-value rows inside the item
      const kvRows: [string, string][] = [];

      kvRows.push(['Mode of Transport', modeLabel]);
      kvRows.push(['From', item.fromLocation]);
      kvRows.push(['To',   item.toLocation]);
      kvRows.push(['Departure Date', formatDate(item.departureDate)]);
      if (item.arrivalDate) kvRows.push(['Arrival Date', formatDate(item.arrivalDate)]);

      // Amount
      if (item.amountIncludedInRoundTrip) {
        kvRows.push(['Amount', '— (price included in round-trip booking)']);
      } else if (item.amountOriginal != null) {
        const eurStr = item.amountEur != null ? `  (${formatEur(item.amountEur)})` : '';
        kvRows.push(['Amount', `${item.amountOriginal.toFixed(2)} ${item.currencyOriginal}${eurStr}`]);
        // Explicit exchange rate for non-EUR items (accountant requirement)
        if (
          item.currencyOriginal &&
          item.currencyOriginal !== 'EUR' &&
          item.amountEur != null &&
          item.amountOriginal > 0
        ) {
          const rate = item.amountEur / item.amountOriginal;
          kvRows.push(['Exchange Rate', `1 ${item.currencyOriginal} = ${rate.toFixed(4)} EUR`]);
        }
      } else {
        kvRows.push(['Amount', 'Not specified']);
      }

      // Luggage
      if (item.luggageAmountEur) {
        const luggStr = item.luggageAmount != null
          ? `${item.luggageAmount.toFixed(2)} ${item.currencyOriginal}  (${formatEur(item.luggageAmountEur)}) – merged luggage fee`
          : `${formatEur(item.luggageAmountEur)} – merged luggage fee`;
        kvRows.push(['Luggage Fee', luggStr]);
      }

      if (item.companyName) kvRows.push(['Company / Airline', item.companyName]);
      if (item.flightNumber) kvRows.push(['Flight Number', item.flightNumber]);
      if (item.bookingReference) kvRows.push(['Booking Reference', item.bookingReference]);
      if (item.distanceKm) kvRows.push(['Distance', `${item.distanceKm} km`]);
      if (item.numberOfPassengers && item.numberOfPassengers > 1)
        kvRows.push(['Passengers on Booking', String(item.numberOfPassengers)]);
      if (item.comment) kvRows.push(['Comment', item.comment]);
      if (item.manuallyEdited) kvRows.push(['Manually Edited', 'Yes (participant corrected AI values)']);
      if (item.excludedFromReimbursement)
        kvRows.push([
          'Excluded from Reimbursement',
          item.exclusionReason === 'HOSTING_ORG_PAID' ? 'Yes (paid by the hosting organisation)' : 'Yes',
        ]);

      drawKvRows(doc, kvRows);

      // Round-trip note
      if (item.amountIncludedInRoundTrip) {
        doc.font('I').fontSize(9).fillColor('#555555')
          .text('Note: Price covers multiple legs under one booking.', MARGIN_H + 10, doc.y + 4);
        doc.y = doc.y + 16;
      }

      // Linked documents
      const linkedDocNames: string[] = [];
      if (item.documentId) {
        const d = participant.documents.find(x => x.id === item.documentId);
        if (d) linkedDocNames.push(d.renamedFilename);
      }
      if (item.additionalDocumentIds) {
        try {
          const ids = JSON.parse(item.additionalDocumentIds) as string[];
          for (const id of ids) {
            const d = participant.documents.find(x => x.id === id);
            if (d && !linkedDocNames.includes(d.renamedFilename)) linkedDocNames.push(d.renamedFilename);
          }
        } catch { /* ignore */ }
      }
      if ((item as any).luggageDocumentId) {
        const d = participant.documents.find(x => x.id === (item as any).luggageDocumentId);
        if (d && !linkedDocNames.includes(d.renamedFilename)) linkedDocNames.push(d.renamedFilename);
      }

      if (linkedDocNames.length > 0) {
        doc.font('B').fontSize(8.5).fillColor('#555555')
          .text('Linked Documents:', MARGIN_H + 10, doc.y + 6);
        for (const name of linkedDocNames) {
          doc.font('R').fontSize(8.5).fillColor('#333333')
            .text(`• ${name}`, MARGIN_H + 22, doc.y + 2);
        }
      }

      doc.y = doc.y + 12;
    }

    // ── SECTION 4: Document Index ────────────────────────────────────────────
    if (doc.y > 620) doc.addPage();
    else doc.moveDown(1.5);

    sectionHeading(doc, 'Supporting Documents Index');
    doc.moveDown(0.5);

    // Uploaded documents
    if (participant.documents.length === 0) {
      doc.font('I').fontSize(10).fillColor('#888888').text('No documents uploaded.', MARGIN_H, doc.y);
    } else {
      for (let i = 0; i < participant.documents.length; i++) {
        if (doc.y > 770) doc.addPage();
        const d = participant.documents[i];
        const typeLabel = DOC_TYPE_LABELS[d.documentType] || 'Document';
        const size = formatFileSize(d.fileSize);
        doc.font('B').fontSize(9.5).fillColor('#111111')
          .text(`${i + 1}.  ${d.renamedFilename}`, MARGIN_H, doc.y);
        doc.font('R').fontSize(8.5).fillColor('#666666')
          .text(`     ${typeLabel}  ·  ${size}  ·  Uploaded ${formatDate(d.uploadDate)}`, MARGIN_H, doc.y + 1);
        doc.y = doc.y + 6;
      }
    }

    // Declarations on honor
    if (participant.declarationsOnHonor.length > 0) {
      doc.moveDown(0.8);
      doc.font('B').fontSize(10).fillColor('#333333').text('Declarations on Honor', MARGIN_H, doc.y);
      doc.moveDown(0.3);
      for (const d of participant.declarationsOnHonor) {
        if (doc.y > 770) doc.addPage();
        const typeLabel = DOC_TYPE_LABELS[d.missingDocumentType] || 'Document';
        doc.font('R').fontSize(9.5).fillColor('#111111')
          .text(`• Declaration on Honor – ${typeLabel}  (${formatDate(d.declarationDate)})`, MARGIN_H + 10, doc.y);
      }
    }

    // Declarations of travel
    if (participant.declarationsOfTravel.length > 0) {
      doc.moveDown(0.8);
      doc.font('B').fontSize(10).fillColor('#333333').text('Declarations of Travel', MARGIN_H, doc.y);
      doc.moveDown(0.3);
      for (const d of participant.declarationsOfTravel) {
        if (doc.y > 770) doc.addPage();
        const modeLabel = TRANSPORT_LABELS[d.modeOfTransport] || d.modeOfTransport;
        doc.font('R').fontSize(9.5).fillColor('#111111')
          .text(`• ${modeLabel}: ${d.fromPlace} → ${d.toPlace}  –  ${formatDate(d.travelDate)}  (signed ${formatDate(d.signedAt)})`, MARGIN_H + 10, doc.y);
      }
    }

    doc.end();
  });
}

// ── Drawing helpers ──────────────────────────────────────────────────────────

function sectionHeading(doc: PDFKit.PDFDocument, title: string) {
  const y = doc.y;
  // Background bar
  doc.rect(MARGIN_H, y, CONTENT_W, 22).fill('#1e293b');
  doc.font('B').fontSize(12).fillColor('#ffffff')
    .text(title, MARGIN_H + 10, y + 5, { width: CONTENT_W - 20, lineBreak: false });
  doc.fillColor('#000000');
  doc.y = y + 28;
}

function drawTable(doc: PDFKit.PDFDocument, rows: [string, string][], startY: number) {
  const labelW = 210;
  const valueW = CONTENT_W - labelW;
  let y = startY;

  for (let i = 0; i < rows.length; i++) {
    const [label, value] = rows[i];
    const bg = i % 2 === 0 ? '#f8fafc' : '#ffffff';
    const rowH = 22;

    doc.rect(MARGIN_H, y, CONTENT_W, rowH).fill(bg);

    // Light border
    doc.rect(MARGIN_H, y, CONTENT_W, rowH)
      .strokeColor('#e2e8f0').lineWidth(0.5).stroke();

    doc.font('B').fontSize(9).fillColor('#555555')
      .text(label, MARGIN_H + 8, y + 7, { width: labelW - 8, lineBreak: false });
    doc.font('R').fontSize(9.5).fillColor('#111111')
      .text(value, MARGIN_H + labelW + 4, y + 6, { width: valueW - 4, lineBreak: false });

    y += rowH;
  }

  doc.fillColor('#000000');
  doc.y = y;
}

function drawItemHeader(doc: PDFKit.PDFDocument, text: string, y: number) {
  doc.rect(MARGIN_H, y, CONTENT_W, 20).fill('#f1f5f9');
  doc.rect(MARGIN_H, y, CONTENT_W, 20)
    .strokeColor('#cbd5e1').lineWidth(0.5).stroke();
  doc.font('B').fontSize(10).fillColor('#1e293b')
    .text(text, MARGIN_H + 8, y + 5, { width: CONTENT_W - 16, lineBreak: false });
  doc.fillColor('#000000');
}

function drawKvRows(doc: PDFKit.PDFDocument, rows: [string, string][]) {
  const labelW = 170;
  const valueW = CONTENT_W - labelW - 20;
  const leftX  = MARGIN_H + 10;

  for (const [label, value] of rows) {
    if (doc.y > 760) doc.addPage();

    const beforeY = doc.y;
    // Draw value first to measure height
    doc.font('R').fontSize(9).fillColor('#111111')
      .text(value, leftX + labelW, beforeY + 2, { width: valueW });
    const afterY = doc.y;
    const rowH = Math.max(afterY - beforeY, 14);

    // Now draw label at same y
    doc.font('B').fontSize(9).fillColor('#666666')
      .text(label, leftX, beforeY + 2, { width: labelW - 4, lineBreak: false });

    // Light separator
    doc.moveTo(MARGIN_H + 10, doc.y)
      .lineTo(PAGE_W - MARGIN_H - 10, doc.y)
      .strokeColor('#f0f0f0').lineWidth(0.3).stroke();

    doc.y = afterY + 3;
    doc.fillColor('#000000');
  }
}

// ── Document appending (pdf-lib) ─────────────────────────────────────────────

async function appendDocuments(
  structuredBuffer: Buffer,
  participantId: string
): Promise<Buffer> {
  const storage = getStorageService();

  // Load all participant data needed for document paths
  const participant = await prisma.participant.findUnique({
    where: { id: participantId },
    include: {
      documents: { orderBy: { uploadDate: 'asc' } },
      declarationsOfTravel: { orderBy: { createdAt: 'asc' } },
    },
  });

  if (!participant) return structuredBuffer;

  const mergedDoc = await LibPDFDocument.create();

  // Copy structured pages first
  const structuredPdf = await LibPDFDocument.load(structuredBuffer);
  const structuredPages = await mergedDoc.copyPages(structuredPdf, structuredPdf.getPageIndices());
  for (const page of structuredPages) mergedDoc.addPage(page);

  // Append each uploaded document
  for (const doc of participant.documents) {
    try {
      const buffer = await storage.retrieve(doc.storedFilePath);
      await appendFilePage(mergedDoc, buffer, doc.mimeType);
    } catch (err) {
      console.error(`[AuditPDF] Could not append document ${doc.storedFilePath}:`, err);
    }
  }

  // Append Declaration of Travel PDFs
  for (const decl of participant.declarationsOfTravel) {
    if (!decl.generatedPdfPath) continue;
    try {
      const buffer = await storage.retrieve(decl.generatedPdfPath);
      const declPdf = await LibPDFDocument.load(buffer);
      const pages = await mergedDoc.copyPages(declPdf, declPdf.getPageIndices());
      for (const page of pages) mergedDoc.addPage(page);
    } catch (err) {
      console.error(`[AuditPDF] Could not append declaration PDF ${decl.generatedPdfPath}:`, err);
    }
  }

  return Buffer.from(await mergedDoc.save());
}

async function appendFilePage(
  mergedDoc: LibPDFDocument,
  buffer: Buffer,
  mimeType: string
): Promise<void> {
  const A4_W = 595.28;
  const A4_H = 841.89;

  if (mimeType === 'application/pdf') {
    const srcPdf = await LibPDFDocument.load(buffer, { ignoreEncryption: true });
    const pages = await mergedDoc.copyPages(srcPdf, srcPdf.getPageIndices());
    for (const page of pages) mergedDoc.addPage(page);
    return;
  }

  // For images: convert WEBP → PNG first, then embed
  let imageBuffer = buffer;
  let finalMime = mimeType;

  if (mimeType === 'image/webp' || mimeType === 'image/gif' || mimeType === 'image/tiff') {
    imageBuffer = await sharp(buffer).png().toBuffer();
    finalMime = 'image/png';
  }

  let embeddedImage;
  try {
    if (finalMime === 'image/jpeg' || finalMime === 'image/jpg') {
      embeddedImage = await mergedDoc.embedJpg(imageBuffer);
    } else if (finalMime === 'image/png') {
      embeddedImage = await mergedDoc.embedPng(imageBuffer);
    } else {
      // Try PNG as fallback
      const converted = await sharp(buffer).png().toBuffer();
      embeddedImage = await mergedDoc.embedPng(converted);
    }
  } catch {
    // Skip this file if embedding fails
    return;
  }

  const page = mergedDoc.addPage([A4_W, A4_H]);
  const { width, height } = embeddedImage;
  const PADDING = 20;
  const maxW = A4_W - PADDING * 2;
  const maxH = A4_H - PADDING * 2;
  const scale = Math.min(maxW / width, maxH / height);
  const scaledW = width * scale;
  const scaledH = height * scale;

  page.drawImage(embeddedImage, {
    x: (A4_W - scaledW) / 2,
    y: (A4_H - scaledH) / 2,
    width: scaledW,
    height: scaledH,
  });
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate the full National Agency Audit PDF for a participant.
 * Returns a Buffer containing the merged PDF ready to stream to the client.
 */
export async function generateAuditPdf(participantId: string): Promise<Buffer> {
  const structured = await buildStructuredPdf(participantId);
  return appendDocuments(structured, participantId);
}
